# Generated by Django 5.2.8 on 2025-12-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
